//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time_Group_Corporation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agreement()
        {
            this.LetterOfCredits = new HashSet<LetterOfCredit>();
            this.ItemsPerAgreements = new HashSet<ItemsPerAgreement>();
        }
    
        public string AmandaNum { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
        public double TotalAmount { get; set; }
        public System.DateTime AgreementDate { get; set; }
        public string Issuer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LetterOfCredit> LetterOfCredits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsPerAgreement> ItemsPerAgreements { get; set; }
    }
}
