//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time_Group_Corporation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangesHistory
    {
        public int Id { get; set; }
        public string LCNumber { get; set; }
        public string AmandaNum { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string ChangedBy { get; set; }
        public string FeildChanged { get; set; }
        public System.DateTime ChangedOn { get; set; }
    }
}
