//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time_Group_Corporation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsPerAgreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemsPerAgreement()
        {
            this.Reductions = new HashSet<Reduction>();
        }
    
        public int Id { get; set; }
        public string AgreementDesc { get; set; }
        public string Department { get; set; }
        public Nullable<double> OrignalAmount { get; set; }
        public string Status { get; set; }
        public string FinalRelease { get; set; }
        public double FinalAmount { get; set; }
        public string Clause { get; set; }
        public string AgreementAmandaNum { get; set; }
    
        public virtual Agreement Agreement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reduction> Reductions { get; set; }
    }
}
