//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time_Group_Corporation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterOfCredit
    {
        public string LCNumber { get; set; }
        public string LCType { get; set; }
        public string Applicant { get; set; }
        public string Beneficiary { get; set; }
        public string Bank { get; set; }
        public double LCAmount { get; set; }
        public System.DateTime LCDate { get; set; }
        public string Project { get; set; }
        public string Agreement_AmandaNum { get; set; }
        public System.DateTime LCRenewalDate { get; set; }
    
        public virtual Agreement Agreement { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
