//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time_Group_Corporation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reduction
    {
        public int Id { get; set; }
        public System.DateTime Reductions { get; set; }
        public double percentage { get; set; }
        public int ItemsPerAgreementId { get; set; }
        public System.DateTime NotfyStartDate { get; set; }
    
        public virtual ItemsPerAgreement ItemsPerAgreement { get; set; }
    }
}
